### ISSUE TITLE
Suggestion: Warning upon sending spine commands before init

### ISSUE THREAD

**Issue by Sojens** [kercre123/vic-go#2]
When the spine has not yet been initialized, a warning should appear in the command-line, for easy notice that something is not being done correctly.

**Comment by kercre123** [comment]
Setting the motors and LEDs should already return errors if the spine isn't initiated. It is best practice to not have functions in a wrapper print directly to console, and for every stdout to be done by user-created code. vic-go is not at that point (it's in an early, debug state), but eventually I would like to get it to be. I did miss it in some spots though and that should now be fixed. Make sure to check for errors on your own like:

```
err := ThingFunction()
if err != nil {
      fmt.Println(err)
      return
}
```
